apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasklist
  template:
    metadata:
      labels:
        app: tasklist
    spec:
      containers:
      - name: tasklist
        image: your-dockerhub-username/tasklist:latest
        ports:
        - containerPort: 8080
