apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasklist
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s
    repoURL: 'https://github.com/nondumison739/Tasklist'
    targetRevision: HEAD
  project: default
